CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TelegramId" bigint NOT NULL,
    "Username" character varying(100) NOT NULL,
    "Elo" integer NOT NULL,
    "GamesPlayed" integer NOT NULL,
    "Wins" integer NOT NULL,
    "Losses" integer NOT NULL,
    "Draws" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastActiveAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "GameInvites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FromUserId" integer NOT NULL,
    "ToUserId" integer NOT NULL,
    "Status" integer NOT NULL,
    "TimeControl" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    CONSTRAINT "PK_GameInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GameInvites_Users_FromUserId" FOREIGN KEY ("FromUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GameInvites_Users_ToUserId" FOREIGN KEY ("ToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Games" (
    "Id" uuid NOT NULL,
    "WhitePlayerId" integer NOT NULL,
    "BlackPlayerId" integer NOT NULL,
    "PGN" text NOT NULL,
    "FEN" text NOT NULL,
    "Status" integer NOT NULL,
    "Result" integer,
    "TimeControl" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "WinnerId" integer,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Games_Users_BlackPlayerId" FOREIGN KEY ("BlackPlayerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Games_Users_WhitePlayerId" FOREIGN KEY ("WhitePlayerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "MatchmakingQueue" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "MinElo" integer NOT NULL,
    "MaxElo" integer NOT NULL,
    "TimeControl" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MatchmakingQueue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MatchmakingQueue_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Moves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameId" uuid NOT NULL,
    "MoveNumber" integer NOT NULL,
    "SAN" character varying(10) NOT NULL,
    "FEN" text NOT NULL,
    "TimeSpentMs" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Moves" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Moves_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GameInvites_FromUserId" ON "GameInvites" ("FromUserId");

CREATE INDEX "IX_GameInvites_Status" ON "GameInvites" ("Status");

CREATE INDEX "IX_GameInvites_ToUserId" ON "GameInvites" ("ToUserId");

CREATE INDEX "IX_Games_BlackPlayerId" ON "Games" ("BlackPlayerId");

CREATE INDEX "IX_Games_CreatedAt" ON "Games" ("CreatedAt");

CREATE INDEX "IX_Games_Status" ON "Games" ("Status");

CREATE INDEX "IX_Games_WhitePlayerId" ON "Games" ("WhitePlayerId");

CREATE INDEX "IX_MatchmakingQueue_MinElo_MaxElo" ON "MatchmakingQueue" ("MinElo", "MaxElo");

CREATE INDEX "IX_MatchmakingQueue_TimeControl" ON "MatchmakingQueue" ("TimeControl");

CREATE UNIQUE INDEX "IX_MatchmakingQueue_UserId" ON "MatchmakingQueue" ("UserId");

CREATE INDEX "IX_Moves_GameId" ON "Moves" ("GameId");

CREATE INDEX "IX_Moves_GameId_MoveNumber" ON "Moves" ("GameId", "MoveNumber");

CREATE INDEX "IX_Users_Elo" ON "Users" ("Elo");

CREATE UNIQUE INDEX "IX_Users_TelegramId" ON "Users" ("TelegramId");

CREATE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310140548_InitialCreate', '10.0.3');

COMMIT;

